# -*- coding: utf-8 -*-
"""run_with_tunnel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-TNXkNUHeFd6Aon-Z9nYVnbkmp3A5JXE
"""

import subprocess
import threading
import time
import socket
import re

PORT = 7860


# =============================
# WAIT WEBUI READY
# =============================
def wait_port(port):
    print("⏳ Waiting WebUI server...")
    while True:
        s = socket.socket()
        try:
            s.connect(("127.0.0.1", port))
            s.close()
            print("✅ WebUI detected!")
            break
        except:
            time.sleep(2)


# =============================
# CLOUDFLARE
# =============================
def start_cloudflare():
    print("🌐 Starting Cloudflare Tunnel...")
    p = subprocess.Popen(
        ["cloudflared", "tunnel", "--url", f"http://127.0.0.1:{PORT}"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True
    )

    for line in p.stdout:
        if "trycloudflare.com" in line:
            url = re.search(r"(https://[-0-9a-zA-Z]+\.trycloudflare\.com)", line)
            if url:
                print(f"✅ Cloudflare URL: {url.group(1)}")
                break


# =============================
# PINGGY
# =============================
def start_pinggy():
    print("🌐 Starting Pinggy Tunnel...")
    subprocess.Popen(
        f"ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:{PORT} a.pinggy.io",
        shell=True
    )


# =============================
# LOCALTUNNEL
# =============================
def start_localtunnel():
    print("🌐 Starting LocalTunnel...")
    p = subprocess.Popen(
        ["lt", "--port", str(PORT)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True
    )

    for line in p.stdout:
        if "your url is:" in line.lower():
            print("✅ LocalTunnel:", line.strip())
            break


# =============================
# START WEBUI
# =============================
def start_webui():
    subprocess.Popen(
        ["python", "launch.py", "--listen", "--port", str(PORT)]
    )


# =============================
# MAIN
# =============================
print("🚀 Starting Stable Diffusion WebUI...")

threading.Thread(target=start_webui).start()

wait_port(PORT)

print("\n🚀 Starting tunnels...\n")

threading.Thread(target=start_cloudflare).start()
threading.Thread(target=start_pinggy).start()
threading.Thread(target=start_localtunnel).start()

while True:
    time.sleep(60)