# -*- coding: utf-8 -*-
"""run_with_tunnel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-TNXkNUHeFd6Aon-Z9nYVnbkmp3A5JXE
"""
import subprocess
import threading
import time
import socket
import re

PORT = 7860


# =============================
# WAIT WEBUI
# =============================
def wait_port(port):
    print("⏳ Waiting WebUI server...")
    while True:
        s = socket.socket()
        try:
            s.connect(("127.0.0.1", port))
            s.close()
            print("✅ WebUI detected!")
            break
        except:
            time.sleep(2)


# =============================
# OUTPUT READER (NON BLOCKING)
# =============================
def stream_output(proc, name, pattern):
    for line in iter(proc.stdout.readline, ''):
        line = line.strip()
        if not line:
            continue

        if pattern in line:
            url = re.search(r"(https://[^\s]+)", line)
            if url:
                print(f"✅ {name} URL:", url.group(1))
                break


# =============================
# CLOUDFLARE
# =============================
def start_cloudflare():
    print("🌐 Starting Cloudflare Tunnel...")

    p = subprocess.Popen(
        ["cloudflared", "tunnel", "--url", f"http://127.0.0.1:{PORT}"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )

    stream_output(p, "Cloudflare", "trycloudflare.com")


# =============================
# PINGGY (TTY FIX + PARALLEL)
# =============================
def start_pinggy():
    print("🌐 Starting Pinggy Tunnel...")

    cmd = [
        "ssh",
        "-tt",
        "-o", "StrictHostKeyChecking=no",
        "-o", "ServerAliveInterval=30",
        "-p", "443",
        f"-R0:localhost:{PORT}",
        "a.pinggy.io"
    ]

    p = subprocess.Popen(
        cmd,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )

    # auto ENTER (pinggy banner fix)
    time.sleep(2)
    try:
        p.stdin.write("\n")
        p.stdin.flush()
    except:
        pass

    url_found = False

    for line in iter(p.stdout.readline, ''):
        line = line.strip()

        # tampilkan log pinggy supaya kelihatan hidup
        print("[PINGGY]", line)

        if "pinggy.link" in line:
            import re
            url = re.search(r"(https://[^\s]+)", line)
            if url:
                print(f"✅ Pinggy URL: {url.group(1)}")
                url_found = True
                break

    # fallback — pinggy kadang delay kirim URL
    if not url_found:
        print("⚠️ Pinggy tunnel aktif, menunggu URL (delay dari server)...")

# =============================
# LOCALTUNNEL
# =============================
def start_localtunnel():
    print("🌐 Starting LocalTunnel...")

    p = subprocess.Popen(
        ["lt", "--port", str(PORT)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )

    stream_output(p, "LocalTunnel", "loca.lt")


# =============================
# START WEBUI
# =============================
def start_webui():
    subprocess.Popen(
        ["python", "launch.py", "--listen", "--port", str(PORT)]
    )


# =============================
# MAIN
# =============================
print("🚀 Starting Stable Diffusion WebUI...")

threading.Thread(target=start_webui, daemon=True).start()

wait_port(PORT)

print("\n🚀 Starting tunnels...\n")

threading.Thread(target=start_cloudflare, daemon=True).start()
threading.Thread(target=start_pinggy, daemon=True).start()
threading.Thread(target=start_localtunnel, daemon=True).start()

# keep alive
while True:
    time.sleep(60)
