# -*- coding: utf-8 -*-
"""run_with_tunnel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-TNXkNUHeFd6Aon-Z9nYVnbkmp3A5JXE
"""
import subprocess
import threading
import time
import socket
import re

PORT = 7860


# =============================
# WAIT WEBUI
# =============================
def wait_port(port):
    print("⏳ Waiting WebUI server...")
    while True:
        s = socket.socket()
        try:
            s.connect(("127.0.0.1", port))
            s.close()
            print("✅ WebUI detected!")
            break
        except:
            time.sleep(2)


# =============================
# OUTPUT READER (NON BLOCKING)
# =============================
def stream_output(proc, name, pattern):
    for line in iter(proc.stdout.readline, ''):
        line = line.strip()
        if not line:
            continue

        if pattern in line:
            url = re.search(r"(https://[^\s]+)", line)
            if url:
                print(f"✅ {name} URL:", url.group(1))
                break


# =============================
# CLOUDFLARE
# =============================
def start_cloudflare():
    print("🌐 Starting Cloudflare Tunnel...")

    p = subprocess.Popen(
        ["/usr/bin/cloudflared", "tunnel", "--url", f"http://127.0.0.1:{PORT}"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )

    for line in iter(p.stdout.readline, ''):
        if "trycloudflare.com" in line:
            import re
            url = re.search(r"(https://[^\s]+)", line)
            if url:
                print(f"✅ Cloudflare URL: {url.group(1)}")
                break

# =============================
# PINGGY (TTY FIX + PARALLEL)
# =============================
def start_pinggy():
    print("🌐 Starting Pinggy Tunnel...")

    import subprocess, time, requests, re

    cmd = [
        "ssh",
        "-tt",
        "-o", "StrictHostKeyChecking=no",
        "-o", "ServerAliveInterval=30",
        "-p", "443",
        f"-R0:localhost:{PORT}",
        "a.pinggy.io"
    ]

    # jalankan ssh tanpa blocking
    subprocess.Popen(cmd)

    # tunggu tunnel benar-benar aktif
    time.sleep(8)

    # coba ambil URL beberapa kali
    for _ in range(10):
        try:
            r = requests.get("http://localhost:4040/api/tunnels", timeout=3)
            data = r.json()

            for t in data["tunnels"]:
                if "pinggy.link" in t["public_url"]:
                    print(f"✅ Pinggy URL: {t['public_url']}")
                    return
        except:
            pass

        time.sleep(3)

    print("⚠️ Pinggy tunnel aktif tapi URL belum terdeteksi (delay server)")
# =============================
# LOCALTUNNEL
# =============================
def start_localtunnel():
    print("🌐 Starting LocalTunnel...")

    p = subprocess.Popen(
        ["lt", "--port", str(PORT)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )

    stream_output(p, "LocalTunnel", "loca.lt")


# =============================
# START WEBUI
# =============================
def start_webui():
    subprocess.Popen(
        ["python", "launch.py", "--listen", "--port", str(PORT)]
    )


# =============================
# MAIN
# =============================
print("🚀 Starting Stable Diffusion WebUI...")

threading.Thread(target=start_webui, daemon=True).start()

wait_port(PORT)

print("\n🚀 Starting tunnels...\n")

threading.Thread(target=start_cloudflare, daemon=True).start()
threading.Thread(target=start_pinggy, daemon=True).start()
threading.Thread(target=start_localtunnel, daemon=True).start()

# keep alive
while True:
    time.sleep(60)
